# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         POE-Component-SimpleLog
version:      1.04
version_from: lib/POE/Component/SimpleLog.pm
installdirs:  site
requires:
    Carp:                          0
    POE:                           0
    Time::HiRes:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
license: perl
