--- #YAML:1.0
name:                POE-Component-SimpleLog
version:             1.05
abstract:            Perl extension to manage a simple logging system for POE.
license:             perl
author:              
    - Apocalypse <APOCAL@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Carp:                          0
    POE:                           0
    Test::CheckManifest:           0
    Test::Distribution:            0
    Test::HasVersion:              0
    Test::Kwalitee:                0
    Test::MinimumVersion:          0
    Test::More:                    0
    Test::Pod:                     0
    Test::Pod::Coverage:           0
    Test::Strict:                  0
    Test::UseAllModules:           0
    Time::HiRes:                   0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
